x-SManager:
  properties:
    - ${NGINX_IMAGE}
    - ${CONSUL_IMAGE}

version: "3"

services:
  consul:
    image: ${CONSUL_IMAGE}
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - smanger-ingress-net
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    restart: unless-stopped

  nginx:
    image: ${NGINX_IMAGE}
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    networks:
      - default
      - smanger-ingress-net

volumes:
  nginx_secrets:

networks:
  smanger-ingress-net:
    name: smanger-ingress-net