x-SManager:
  properties:
    - "Домен: ${DOMAIN}"
    - "Master: ${MASTER_IP}"
    - "Slave: ${SLAVE_IP}"
  side_menu:
    - Ссылки:
        PowerDNSAdmin: http://${ODS_SM_SERVER_IP}:${EXT_PORT}
  ui_edit_vars:
    Домен: DOMAIN
    Master IP: MASTER_IP
    Slave IP: SLAVE_IP
    Внешний порт PowerDNSAdmin: EXT_PORT


version: '3'

services:
  powerdns:
    image: pschiffe/pdns-mysql:alpine
    ports:
      - "53:53/udp"
      - "53:53"
#      - "8088:8081"
    extra_hosts:
      - 'ns1.${DOMAIN}:${SLAVE_IP}'
      - 'ns2.${DOMAIN}:${MASTER_IP}'
    hostname: ns2.${DOMAIN}
    environment:
      PDNS_api_key: "${ODS_SM_GENERATE_RANDOM_apikey_20}"
      PDNS_master: "yes"
      PDNS_api: "yes"
      PDNS_webserver: "yes"
      PDNS_webserver_address: "0.0.0.0"
      PDNS_webserver_allow_from: "0.0.0.0/0"
      PDNS_webserver_password: "${ODS_SM_GENERATE_RANDOM_1_30}"
      PDNS_version_string: "anonymous"
      PDNS_default_ttl: "1500"
      PDNS_allow_axfr_ips: "${SLAVE_IP}"
      PDNS_only_notify: "${SLAVE_IP}"
#default: a.misconfigured.dns.server.invalid hostmaster.@ 0 10800 3600 604800 3600
# @ is replaced by the zone name.
      PDNS_default_soa_content: "ns2.${DOMAIN} hostmaster.@ 0 10800 3600 604800 3600"
      MYSQL_ENV_MYSQL_HOST: "mysql"
      MYSQL_ENV_MYSQL_PASSWORD: "${ODS_SM_GENERATE_RANDOM_dbuserpassword_20}"
      MYSQL_ENV_MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ENV_MYSQL_USER: "${DB_USERNAME}"
      MYSQL_ENV_MYSQL_ROOT_PASSWORD: "${ODS_SM_GENERATE_RANDOM_dbrootpassword_20}"
    depends_on:
      - mysql
#    links:
#      - mysql

  powerdns-admin:
    image: aescanero/powerdns-admin
    ports:
      - "${EXT_PORT}:9191"
    environment:
      PDNS_PROTO: "http"
      PDNS_API_KEY: "${ODS_SM_GENERATE_RANDOM_apikey_20}"
      PDNS_HOST: "powerdns"
      PDNS_PORT: "8081"
      PDNSADMIN_SECRET_KEY: "${ODS_SM_GENERATE_RANDOM_0_20}"
      PDNSADMIN_SQLA_DB_HOST: "mysql"
      PDNSADMIN_SQLA_DB_PASSWORD: "${ODS_SM_GENERATE_RANDOM_dbuserpassword_20}"
      PDNSADMIN_SQLA_DB_NAME: "${DB_NAME}"
      PDNSADMIN_SQLA_DB_USER: "${DB_USERNAME}"
    depends_on:
      - powerdns
      - mysql
#    links:
#      - mysql
#      - powerdns

  mysql:
    image: mariadb:10.5-focal
    command: --net-read-timeout=2000 --innodb_use_native_aio=0 --innodb_flush_method=fsync
    environment:
      MARIADB_PASSWORD: "${ODS_SM_GENERATE_RANDOM_dbuserpassword_20}"
      MARIADB_DATABASE: "${DB_NAME}"
      MARIADB_USER: "${DB_USERNAME}"
      MARIADB_ROOT_PASSWORD: "${ODS_SM_GENERATE_RANDOM_dbrootpassword_20}"
#      MYSQL_INITDB_SKIP_TZINFO: "1"
    volumes:
    - ./pdnsdb:/var/lib/mysql
    ports:
#      - "3306:3306"
      - "3306"
#volumes:
#  pdnsdb:
