x-SManager:
  side_menu:
    - Links:
        IP http: http://${ODS_SM_SERVER_IP}:${EXT_PORT}
        Domain https: https://${SITE_DOMAIN}
  properties:
    - "Domain: ${SITE_DOMAIN}"
    - "External port without SSL: ${EXT_PORT}"
  ui_edit_vars:
    External port: EXT_PORT
    Domain: SITE_DOMAIN
  script:
    - wget -O nginx.conf https://raw.githubusercontent.com/leftusername/smanager-templates/github/Nextcloud/nginx.conf
    - docker-compose up -d consul-client
    - |
      docker-compose exec consul-client consul services register\
      -name=${ODS_SM_GENERATE_UUIDv4_0}\
      -address=${ODS_SM_GENERATE_UUIDv4_0}\
      -port=80\
      -tag=nginx\
      -meta="site_domain=${SITE_DOMAIN}"\
      -meta="compose_name=${ODS_SM_COMPOSE_SYS_NAME}"

version: '3'

services:
  db:
    image: mariadb:11.0.2
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    environment:
      - MYSQL_ROOT_PASSWORD=${ODS_SM_GENERATE_RANDOM_RootPASS_20}
      - MYSQL_PASSWORD=${ODS_SM_GENERATE_RANDOM_UserPASS_20}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    volumes:
      - ./mysql:/var/lib/mysql

  app:
    image: ${NEXTCLOUD_IMAGE}
    restart: always
    links:
      - db
    environment:
      - MYSQL_PASSWORD=${ODS_SM_GENERATE_RANDOM_UserPASS_20}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=${ODS_SM_SERVER_IP}, ${SITE_DOMAIN}
    volumes:
      - ./nextcloud:/var/www/html

  web:
    image: nginx
    hostname: ${ODS_SM_GENERATE_UUIDv4_0}
    restart: always
    ports:
      - ${EXT_PORT}:80
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nextcloud:/var/www/html
    networks:
      - smanager-ingress-net
      - default

  consul-client:
    command:  agent -node=client-${ODS_SM_GENERATE_UUIDv4_0} -retry-join=consul
    image: ${CONSUL_IMAGE}
    networks:
      - smanager-ingress-net

networks:
  smanager-ingress-net:
    name: smanager-ingress-net

#volumes:
#  nextcloud:
#  db: