x-SManager:
  ui_edit_vars:
    Domain: SITE_DOMAIN
  script:
    - docker-compose up -d consul-client
    - |
      docker-compose exec consul-client consul services register\
      -name=${ODS_SM_GENERATE_UUIDv4_0}\
      -address=${ODS_SM_GENERATE_UUIDv4_0}\
      -port=80\
      -tag=nginx\
      -meta="site_domain=${SITE_DOMAIN}"

version: "3"
services:
  consul-client:
    command:  agent -node=client-${ODS_SM_GENERATE_UUIDv4_0} -retry-join=consul
    image: ${CONSUL_IMAGE}
    networks:
      - smanager-ingress-net
    restart: unless-stopped

# This example inbound service. replace it yours. add to your service hostname and networks from this example
  test-service:
    # 'hostname' is not compatible with old docker.
    # if you use old version of docker, when you must use 'container_name' instead hostname
#    container_name: ${ODS_SM_GENERATE_UUIDv4_0}
    hostname: ${ODS_SM_GENERATE_UUIDv4_0}
    image: nginx:1.23.3-alpine
# port 80 and 443 should be closed
#    ports:
#    - 80
    networks:
      - smanager-ingress-net
      - default

networks:
  smanager-ingress-net:
    name: smanager-ingress-net
    external: true