x-SManager:
  script:
    - docker-compose up consul-client
    - |
      docker-compose exec consul-client consul services register\
      -name=${SITE_DOMAIN}\
      -address=${ODS_SM_GENERATE_UUIDv4_0}\
      -port=80\
      -tag=nginx\
      -meta="site_domain=${SITE_DOMAIN}"\
      -meta="compose_name=${ODS_SM_COMPOSE_NAME}"

version: "3"
  consul-client:
    command:  agent -node=client-1 -retry-join=consul
    image: ${CONSUL_IMAGE}
    networks:
    - smanger-ingress-net

  test-service:
    hostname: ${ODS_SM_GENERATE_UUIDv4_0}
    image: nginx:1.23.3-alpine
    ports:
    - 80
    networks:
    - smanger-ingress-net