version: '3.1'

services:
  mongo:
    image: ${MONGO_IMAGE}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${ODS_SM_GENERATE_RANDOM_MongoRootPASS_20}
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_data/db:/data/db

