x-SManager:
  side_menu:
    - Ссылки:
        Nexus web: http://${ODS_SM_SERVER_IP}:${WEB_PORT}
  ui_edit_vars:
    Порт Web: WEB_PORT
    Порт API: API_PORT

version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - ${WEB_PORT}:8080
      - ${API_PORT}:50000
    container_name: jenkins-lts
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - /usr/local/bin/docker:/usr/local/bin/docker


