x-SManager:
  side_menu:
    - Links:
        Documentation: https://github.com/itzg/docker-minecraft-server/tree/2022.15.0
  ui_edit_vars:
    Timezone: TZ
    CONSOLE: CONSOLE
    TYPE: TYPE
    VERSION: VERSION
    MEMORY: MEMORY
    SERVER_NAME: SERVER_NAME
    MOTD: MOTD
    LEVEL_TYPE: LEVEL_TYPE
    LEVEL: LEVEL
    MODE: MODE
    FORCE_GAMEMODE: FORCE_GAMEMODE
    DIFFICULTY: DIFFICULTY
    HARDCORE: HARDCORE
    ANNOUNCE_PLAYER_ACHIEVEMENTS: ANNOUNCE_PLAYER_ACHIEVEMENTS
    MAX_PLAYERS: MAX_PLAYERS
    PVP: PVP
    ALLOW_FLIGHT: ALLOW_FLIGHT
    MAX_WORLD_SIZE: MAX_WORLD_SIZE
    MAX_BUILD_HEIGHT: MAX_BUILD_HEIGHT
    SPAWN_ANIMALS: SPAWN_ANIMALS
    SPAWN_MONSTERS: SPAWN_MONSTERS
    SPAWN_NPCS: SPAWN_NPCS
    SPAWN_PROTECTION: SPAWN_PROTECTION
    VIEW_DISTANCE: VIEW_DISTANCE
    ONLINE_MODE: ONLINE_MODE
    SNOOPER_ENABLED: SNOOPER_ENABLED
    ENABLE_COMMAND_BLOCK: ENABLE_COMMAND_BLOCK

services:
  minecraft:
    # Image tag (replace with yours)
    image: ${IMAGE}
    volumes:
      - ./data:/data
      - ./plugins:/plugins:ro
    environment:
      TZ: ${TZ}
      EULA: 'true'
      CONSOLE: ${CONSOLE}
      TYPE: ${TYPE}
      VERSION: ${VERSION}
      MEMORY: ${MEMORY}
      SERVER_NAME: ${SERVER_NAME}
      MOTD: ${MOTD}
      LEVEL_TYPE: ${LEVEL_TYPE}
      LEVEL: ${LEVEL}
      MODE: ${MODE}
      FORCE_GAMEMODE: ${FORCE_GAMEMODE}
      DIFFICULTY: ${DIFFICULTY}
      HARDCORE: ${HARDCORE}
      ANNOUNCE_PLAYER_ACHIEVEMENTS: ${ANNOUNCE_PLAYER_ACHIEVEMENTS}
      MAX_PLAYERS: ${MAX_PLAYERS}
      PVP: ${PVP}
      ALLOW_FLIGHT: ${ALLOW_FLIGHT}
      MAX_WORLD_SIZE: ${MAX_WORLD_SIZE}
      MAX_BUILD_HEIGHT: ${MAX_BUILD_HEIGHT}
      SPAWN_ANIMALS: ${SPAWN_ANIMALS}
      SPAWN_MONSTERS: ${SPAWN_MONSTERS}
      SPAWN_NPCS: ${SPAWN_NPCS}
      SPAWN_PROTECTION: ${SPAWN_PROTECTION}
      VIEW_DISTANCE: ${VIEW_DISTANCE}
      ONLINE_MODE: ${ONLINE_MODE}
      SNOOPER_ENABLED: ${SNOOPER_ENABLED}
      ENABLE_COMMAND_BLOCK: ${ENABLE_COMMAND_BLOCK}
    ports:
      - "25565:25565"
    restart: unless-stopped